// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEe-wONMmhrsvgO_2ZaMGDeb5Ftk2mvsY',
    appId: '1:93688306315:android:108c7f9af8c25f26e0d28e',
    messagingSenderId: '93688306315',
    projectId: 'revive-11dbb',
    storageBucket: 'revive-11dbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkLwS6BwkWUT8dqt1UdjXW0mPvDF34lAk',
    appId: '1:93688306315:ios:b768200b98eafb2be0d28e',
    messagingSenderId: '93688306315',
    projectId: 'revive-11dbb',
    storageBucket: 'revive-11dbb.appspot.com',
    androidClientId: '93688306315-lumbt7d8ekvo3guu3mll1rdg64c64unv.apps.googleusercontent.com',
    iosClientId: '93688306315-lb9tacs3p9v2gs7s72lu6u8sr63ju8ob.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebiblio',
  );
}
